#!/bin/bash

cd ../venv
source bin/activate
echo -ne "\n"
pip list --format=columns > ../scripts/venv_installed.txt
../scripts/list2req.py ../scripts/venv_installed.txt ../scripts/venv_requirements.txt
cd ../scripts
./venv_create
deactivate
